version: "3"

services:
  stock-front-end:
    build: ./stock-front-end/
    container_name: stock-front-end
    restart: always
    ports:
      - "4000:4000"
    command:
      "npm run start"
  stock-back-end:
    build: ./stock-back-end/
    container_name: stock-back-end
    restart: always
    ports:
      - "9000:9000"
    command:
      "/usr/src/stock-back-end/target/universal/stock-1.0-SNAPSHOT/bin/stock -Dplay.http.secret.key=ad31779d4ee49d5ad5162bf1429c32e2e9933f3b"
  nginx-server:
    image: nginx
    container_name: nginx-server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "81:81"
    depends_on:
      - stock-front-end