ARG OPENJDK_TAG=8u212
FROM openjdk:${OPENJDK_TAG}

ARG SBT_VERSION=1.2.8

# Install sbt
RUN \
  curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  sbt sbtVersion

# create destination directory
RUN mkdir -p /usr/src/stock-back-end
WORKDIR /usr/src/stock-back-end

# copy the app, note .dockerignore
COPY . /usr/src/stock-back-end/

# build necessary, even if no static files are needed,
# since it builds the server as well
RUN sbt dist
RUN unzip /usr/src/stock-back-end/target/universal/stock-1.0-SNAPSHOT.zip -d .

# expose 9000 on container
EXPOSE 9000