FROM node:10.16.0

# create destination directory
RUN mkdir -p /usr/src/stock-front-end
WORKDIR /usr/src/stock-front-end

# copy the app, note .dockerignore
COPY . /usr/src/stock-front-end/
RUN npm install

# build necessary, even if no static files are needed,
# since it builds the server as well
RUN npm run build

# expose 4000 on container
EXPOSE 4000

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=4000